### ISSUE TITLE
repository structure?

### ISSUE THREAD

**Issue by ilg-ul** [ckormanyos/real-time-cpp#1]
Hi Christopher,

I appreciate your book and your code, but I'm not very happy with the way this repository is organised. Could you split it and move the tools separate from the sources?

I'm using OS X and the Windows specific tools are of little use for me (not to mention the use of Git for distributing very large binaries, available anyway from their publishers).

Also, a more portable approach would be highly appreciated. For ARM projects you can use Eclipse and the GNU ARM Eclipse plug-ins.

 Thank you,

Liviu

**Comment by wifixcort** [comment]
Hi I like the your book but I'm having serious problems implementing your examples.

I am seeing the previous discussions and I realize that the repository is directed to use an IDE and the process becomes seriously terrible, if that IDE is not used in particular. I think that anyone should implement your examples from a simple terminal

**Comment by ckormanyos** [comment]
Hi. Thanks for the comment. Yes, I am aware of this weakness. Would *nix Makefiles for GNUmake be a good starting point? I could generate these if desired.
Regards, Chris.

**Comment by ilg-ul** [comment]
From my experience with GNU ARM Eclipse, properly written makefiles are quite portable.

However, for Windows, the key is having a new and correctly configured & packed make, otherwise there are countless problems, like line length, paths with spaces, etc.

For those interested, I maintain a Windows Build Tools package that can be used without problems outside GNU ARM Eclipse: http://gnuarmeclipse.github.io/windows-build-tools/.

**Comment by wifixcort** [comment]
A generic Makefile would be a very good idea

**Comment by ckormanyos** [comment]
The various points in this issue have been handled.
Repository structure is now cleaner.
Generic build is supported with various build improvements over the years.
