### ISSUE TITLE
The new Chapter09_07 source code

### ISSUE THREAD

**Issue by aswimman** [ckormanyos/real-time-cpp#15]
Hi Chris - I see that you've added this new section Chapter09_07 source code.   My only question is that there isn't a Chapter 9.7 in your current edition of the book?  Can you explain what this new section is for (appears to be display related)?

Thanks!

(PS. My students are enjoying the class and using your book and software....)

**Comment by ckormanyos** [comment]
A second edition of the book is in progress. Thesecond edition is expected to have Sect. 9.7 contaning a full description of the seven-segment display example. Sorry, I've been a bit terse on this new stuff.

**Comment by aswimman** [comment]
Chris - Great to know!  Sounds like a great example…  let me know when your drop dead date is for corrections.  We are collecting them as we go along…  Do you have an anticipated publishing date yet?   I’m going to be teaching this class again in the fall (starting in mid-August)…

Thanks!
Ken

**Comment by ckormanyos** [comment]
Ken,

Please feel free to send suggestions and corrections any time---actually, the sooner the better. Thanks for your continued interest in the book and sample code.

Thanks again, Chris

**Comment by ckormanyos** [comment]
Closing this issue because the original question has been addressed. New suggestions and corrections can be addressed in new issues.
