### ISSUE TITLE
Permission for Real-Time C++ Book Excerpts

### ISSUE THREAD

**Issue by aswimman** [ckormanyos/real-time-cpp#23]
Hi Chris - Good to chat with you again!  After a one semester break, I should be teaching my course at the University of Puerto Rico - Mayaguez again in August.   I've had two successful classes using your book and I was happy to see that the 2nd Edition is out now!  I've order two books - one for me and one for UPRM.

Question for you (or the publisher).  I would like to take snapshot copies from certain pages from your book to add to my Prezi presentations.  For the first two semesters, I only referenced your book and had the students turn to those pages when needed.  Very awkward especially since I'm teaching live virtually using zoom.us service.  How do I get permission to use your book in this way?  My presentations are not publicly available and limited to the students who are in my course and who have also purchased the book.

I want to ensure that I'm meeting all copyright restrictions with your book and any restrictions that the publisher my have.

Please let me know what I am able to do with your book during class time.

Thanks!
Ken Vaughan
Profesor 
Departamento de Ingeniería Eléctrica y Computadoras 
Recinto Universitario de Mayagüez 
Universidad de Puerto Rico
kenneth.vaughan@upr.edu

**Comment by ckormanyos** [comment]
Hi Ken,

It is good to hear about your successful use of the book. Thank you.

In my opinion, you must adhere to all copyright restrictions from the publisher, Springer Verlag. As far as I know, these are printed in the front matter of the book.

Best regards, Chris
