### ISSUE TITLE
Bought your book but which one is which edition?

### ISSUE THREAD

**Issue by shamun** [ckormanyos/real-time-cpp#24]
From Amazon, I bought your book but i am confused is it first edition i bought or second edition?
![snap](http://i.imgur.com/AmfjTLF.jpg)

Can you please give me the URL for 1st and 2nd edition of your books?

**Comment by niepiekm** [comment]
You have a 1st edition of the book. Here's a link:
https://www.springer.com/us/book/9783642429156
And here's a link to 2nd edition:
https://www.springer.com/us/book/9783662478097

**Comment by shamun** [comment]
Indeed i have 1st edition, i am interested to collect your second edition too.

I am using your book specially for Chromium open source project to interconnect with real-time microcontroller. Chromium use strict C++11. 

Is your second edition completely written on strict C++11 or it mixed with 14, 17 (which i want to avoid practice only stick with C++11)?

**Comment by ckormanyos** [comment]
The 1st edition is C++11 only. The 2nd edition includes uses of C++14.

The C++14 material in the 2nd edition is easy to identify. Most C++14 material is mentioned in the preface to the 2nd edition.

The companion code remains predominantly C++11.

**Comment by ckormanyos** [comment]
The third edition is now available, if this is still relevant.
