### ISSUE TITLE
Building on Linux hangs build when printing GCC version.

### ISSUE THREAD

**Issue by gantzm** [ckormanyos/real-time-cpp#27]
In the file `target/app/make/app_make_linux.gmk` the section:

```
        @$(ECHO) GCC version...
	@$(CC) -xc++ -E -v -
```
hangs waiting for input because of the trailing '-'.  I have removed the trailing dash and the command no longer hangs, though it does give a warning about the options.

**Comment by ckormanyos** [comment]
Sorry about the late response. The Linux build has not been kept up to date, and this is a bit of an error on my side. I will try to look into this.

**Comment by ckormanyos** [comment]
We could consider replacing this witj the simpler short form of the command...
@$(CC) -v

**Comment by gantzm** [comment]
That actually fixes up the problem quite nicely.

**Comment by ckormanyos** [comment]
Great! Thank you for your report and for the help. If you like, you could issue a pull request for the changes you made? But this is completely optional. Best regards, Chris

**Comment by gantzm** [comment]
A pull request has been issued.

**Comment by ckormanyos** [comment]
Done. Thank you for the contribution.
