### ISSUE TITLE
Difficulty in starting work

### ISSUE THREAD

**Issue by sami1369** [ckormanyos/real-time-cpp#270]
The book and git don't have a proper tutorial to start with and the content is very confusing.
 
Please help me to upload the code in the right way

Regards

**Comment by ckormanyos** [comment]
> book and git don't have a proper tutorial to start with and the content is very confusing.

> help me to upload the code in the right way

Thanks for your query @sami1369. Let's start with some basics. You can obtain the code by simply clicking on the "code" button and downloading the ZIP archive. See the picture below.

![grafik](https://user-images.githubusercontent.com/2404721/179353194-fa197c6e-a8c8-4a1c-95e2-86257c5432af.png)

**Comment by ckormanyos** [comment]
Once you have downloaded the project, we can build one of the samples or the reference application. i can help you along those lines.

What Operating System are you using?

**Comment by sami1369** [comment]
Hi Christopher,

I searched for your email, but unfortunately, I was not successful. I had
to send a message here to you.

My hardware is Arduino UNO, and I don't know what I should do to compile
and upload it on the board?

Kind regards,
Saeid

**Comment by sami1369** [comment]
> Once you have downloaded the project, we can build one of the samples or the reference application. I can help you along those lines.
> 
> What Operating System are you using?

Yes, I downloaded it and put it in a folder where Mingw-w64 is there

**Comment by ckormanyos** [comment]
> I downloaded it and put it in a folder where Mingw-w64 is there

OK. Good.

There are several ways to build and use the companion code. Builds are supported on LINUX, Windows, using GNUmake or CMake. But you are right, the build possibilities can, in fact, be confusing when starting.

A lot of folks have used LINUX systems. Others use Windows. A build system specifically targeting MinGW is not explicitly supported but probably would work with a bit of effort.

It can be easiest to first build for the Windows/LINUX host (in a command shell). As a second step, you can go for an embedded target build.

Of the following choices, how would you like to start?
1. Build in MICROCHIP's ATMEl Studio.
2. Build on LINUX with GNUmake.
3. Build on LINUX with CMake.
4. Build on Windows in Microsoft Visual Studio (using specially ported compilers [here](https://github.com/ckormanyos/real-time-cpp-toolchains)).
5. Standalone build on the Windows command line.

Believe it or not, choice 5 can be extremely straightforward, requiring no added installations, just getting the toolchain, unpacking, moving it and executing the build command line. These exact instructions are shown [here](https://github.com/ckormanyos/real-time-cpp/blob/d006c98f3c433124bc5b057dc36215d50723fa3b/.github/workflows/real-time-cpp.yml#L558). But instead of building with MSBuild (as shown on [line 589](https://github.com/ckormanyos/real-time-cpp/blob/d006c98f3c433124bc5b057dc36215d50723fa3b/.github/workflows/real-time-cpp.yml#L589), a simple command line could be used.

**Comment by ckormanyos** [comment]
> Believe it or not, choice 5 can be extremely straightforward

If you diecde to go this way, that can be simple. When you've unpacked the toolchains, I con provide you with help regarding setting up the command line to build for Windows host.

**Comment by sami1369** [comment]
I downloaded it twice, but the file has a problem and cannot be unpacked. Since it has a large volume, let me download and unpack it again; maybe the problem will be solved.

**Comment by sami1369** [comment]
After After downloading a few times I get error when I want to unzip it: 
![image](https://user-images.githubusercontent.com/30548915/179995755-8ed745cd-9875-47b0-b89c-da7312035be7.png)
can you give me another link to download?

**Comment by sami1369** [comment]
Thanks, I downloaded 7-zip.

I could unzip toolchains

What is the next step?

Thank

**Comment by ckormanyos** [comment]
In your case, I recommend to build for the Windows host on the command line as a first step.

The later steps get you building for the embedded AVR controller. But taking an intermediate step to build for a PC will hopefully boost your confidence and provide a much better feeling for how the build system and toolchains all fit together.

So you need to move a directory, unpack a self extracting ZIP and issue a command line.
Let's get started.

You should set up a topology like this (where you simply have the unpacked repositories real-time-cpp (master) and real-time-cpp-toolchains (master). See the image below.

![grafik](https://user-images.githubusercontent.com/2404721/180029029-3343e464-b385-44f5-84dd-c3d9807507c9.png)

Now you need to do a few manual steps.

- Move the tools: For this please move the directory `real-time-cpp-toolchains-master/ref_app/tools` to `real-time-cpp-master/ref_app/tools`. See picture below.
- Now we unpack the compiler for x86_64. Navigate to the directory `real-time-cpp-master/ref_app/tools/Util/msys64/usr/local`.
- Now locate the archive called `gcc-11.2.0-x86_64-w64-mingw32.exe`.
- Simply double click on that archive file to unpack the `gcc-11.2.0-x86_64-w64-mingw32` toolchain. Say yes to unpack the toolchain.

Now we will build for Windows host.

1. Open a command shell located in the directory `real-time-cpp-master/ref_app`.
2. Execute the command `.\target\build\build.bat x86_64-w64-mingw32 rebuild`.
3. The build begins.
4. Find the executable file `real-time-cpp-master/ref_app/bin/ref_app.exe` and run it. You should see the simulated PC LED _blinking_.

I found an actual bug in the toolchain. So when building, just click OK on any DLL windows that pop up. I will correct this bug soon.

![grafik](https://user-images.githubusercontent.com/2404721/180029942-9b965bc5-faa2-479d-abaa-b89ae7e84386.png)

![grafik](https://user-images.githubusercontent.com/2404721/180031923-62af7609-475a-4376-b79d-b587b844f30b.png)

**Comment by ckormanyos** [comment]
As a second step, if you like this kind of build, we should get you set up with Visual Studio Community 2022, where you can enjoy the comfort of this build in that GUI.

Cc: @sami1369

**Comment by jvco98** [comment]
Hi! I'm having some troubles in setting everything up in a Unix environment. I'm pretty new to it all, but I think I installed GCC correctly using homebrew. I have my Nucleo stm32f446 which I'd like to use but I've been getting some error messages. When following along, I'm stuck here:
<img width="842" alt="Screen Shot 2022-07-28 at 10 59 47 PM" src="https://user-images.githubusercontent.com/22757493/181674207-6844bfb5-e149-4c77-9316-9e52c6affc45.png">
After entering ``` ./target/build/build.sh stm32f446 rebuild
``` i get the error
<img width="564" alt="image" src="https://user-images.githubusercontent.com/22757493/181674595-a5e4d1d9-cb12-4821-9831-3c1788c8b514.png">
Are you familiar with what this would mean? Thanks for any help!

**Comment by ckormanyos** [comment]
> Are you familiar with what this would mean? 

Hi Jeff (@jvco98), I'll take a bit more time for this later. Could you please create another issue for this independent point? I would like to also take this opportunity to sue up some more target builds on MacOS in the Ci setup as we progress.

**Comment by sami1369** [comment]
> 2\. .\target\build\build.bat x86_64-w64-mingw32 rebuild

Hi again, 
Apologies for the late reply, things were a bit crazy around here these days... 

![image](https://user-images.githubusercontent.com/30548915/183583547-c534d208-faf0-4393-9701-84de7039daab.png)

My system cant build the command because above error

**Comment by ckormanyos** [comment]
> cant build the command because above error

OK. It looks mostly there. The build command is successfully finding GNUmake version 4.2.1. Good job @sami1369.

The next issue is that the make system (within the calls executed in GNUmake) is not finding the x86_64 compiler.

You also need to unpack the compiler, which has been cloned as a self-exctracting zip archive.

Did you remember unpack the mingw x86_64 compiler?

**Comment by sami1369** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/30548915/183877780-13995b3b-5986-4379-b93e-007475273782.png)


> > cant build the command because above error
> 
> OK. It looks mostly there. The build command is successfully finding GNUmake version 4.2.1. Good job @sami1369.
> 
> The next issue is that the make system (within the calls executed in GNUmake) is not finding the x86_64 compiler.
> 
> You also need to unpack the compiler, which has been cloned as a self-exctracting zip archive.
> 
> Did you remember unpack the mingw x86_64 compiler?

**Comment by sami1369** [comment]
Do you mean this? 
![image](https://user-images.githubusercontent.com/30548915/183878982-59cc97db-68d4-4ee5-9669-d17060f9b045.png)

**Comment by ckormanyos** [comment]
> Do you mean this?

Yes. My apologies, but the Windows build is actually one of the more complicated ones.

That actually looks good. I'm somewhat surprised the compiler can't be found. Have you tried to run the build again?

**Comment by ckormanyos** [comment]
You can also try to manually run the command shown in the failed run above that prints the GCC compiler version.

Something like:

```sh
tools\Util\msys64\usr\local\gcc-11.2.0-x86_64-w64-mingw32\bin\g++ -v
```
```

**Comment by sami1369** [comment]
Is there a different way to compile?

**Comment by ckormanyos** [comment]
> Is there a different way to compile?

There are numerous ways to compile on Windows, LINUX and MacOS for each supported target.

Each method is described briefly in the documentation at the GitHub page for real-time-cpp, starting around [here](https://github.com/ckormanyos/real-time-cpp#getting-started-with-the-reference-application)

**Comment by ckormanyos** [comment]
My first compilation for standalone AVR years ago used ATMEL Studio available now from MICROCHIP. ATMEL Studio is supported in this repository for the reference application.

Some developers use ARDUINO development environment to learn. This is different from the standalone approach used in this repository, but a great way to familiarize yourself with the AVR world.

**Comment by sami1369** [comment]
The Arduino development environment is an appropriate choice for me because I tackle with every day. I can use Arduino UNO or ESP32. 
do you have any examples related to the book? It will be very helpful to me. 

I can even work with stm32F1xxx series if you have any suggestions. Even though Arduino is more accessible to me.

Now, It is only important for me to be able to continue your book with exercise.

**Comment by ckormanyos** [comment]
Hi @sami1369 I think you are actually rather close to building the reference application either for AVR or for an ARM based core.

Please note that all the book's example projects are actually tested for and developed for an AVR controller, often times using self-made boards in a DIY fashion.

I would like to know how far you got when building the reference application. Where did things stop working?

If you would like to simply install MICROCHIP's ATMEL Studio (available from internet), it can be very straightforward to build the reference application and all the book's examples. Also each target/example is built in the Continuous Integration script.

If you could select one method, I'm pretty sure you are not that far from getting the reference application built and running on a board.

In your opinion, how far did you get and what seems to be failing or breaking down for your build(s)?

**Comment by sami1369** [comment]
Hi Christopher,
I want to practice while reading the book and I think that Atmel Studio is
suitable so that I can compile the book's examples and upload them on AVR
boards like Arduino UNO that use an ATmega328.  Could you please let me
know if this is your suggestion?

and can I use book libraries in Atmel Studio?

**Comment by ckormanyos** [comment]
> ... please let me know if this is your suggestion?

> and can I use book libraries in Atmel Studio?

Yes @sami1369. This is my suggestion based on our discussion up to this point. This is a very simple and good way to use the book's examples on the Windows platform.

Both the reference application as well as each example project (from the book's chapters) have project workspaces for MICROCHIP's ATMEL Studio.

So if you install ATMEL Studio, you can open any of the `*.atsln` files and build the corresponding project.

For example, if you would like to build the reference application (ref_app), you will find `ref_app.atsln` located [here](https://github.com/ckormanyos/real-time-cpp/tree/master/ref_app).

Each example has its *.atsln` file within its example root folder.

**Comment by ckormanyos** [comment]
If you decide to use ATMEL Studio, you should not need any other libraries for these projects other than those that are installed during the standard installation of ATMEL Studio.

The first couple of projects can use the ARDUINO board directly. Later chapters in the book need additional components. Chapter4's examples, for instance, uses additional LEDs that need to be provided.

**Comment by sami1369** [comment]
Hi Christopher,

I use this link to run book examples by the link attached.
https://www.instructables.com/How-to-Load-Programs-to-an-Arduino-UNO-From-Atmel-/

Thank you

**Comment by ckormanyos** [comment]
> I use this link to run book examples by the link attached.

Thank you for providing this informative link.

Does this mean that you can now use ATMEL Studio to build and successfully flash some of the examples into your ARDUINO device?

**Comment by sami1369** [comment]
Yes, it works.

I tested some examples

**Comment by ckormanyos** [comment]
>> Does this mean that you can now use ATMEL Studio to build and successfully flash some of the examples into your ARDUINO device?

> Yes, it works.
> I tested some examples

Great! Good work keeping going to success.

I'll close this issue now. If any other issues arise, please feel free to raise another issue any time.

Kind regards, Chris
