### ISSUE TITLE
Building STL on Linux.

### ISSUE THREAD

**Issue by gantzm** [ckormanyos/real-time-cpp#28]
When running `./target/build/build.sh avr rebuild` the build fails because there is no STL implementation built.  It appears an STL implementation is provided in the `src/utils/STL` directory, but I can find no build files or instructions for building this implementation.

Is the `src/utils/STL` used, or is there a different STL dependency that needs to be downloaded and built?

**Comment by gantzm** [comment]
This appears to be the issue:

The file `target/app/make/app_make.gmk` has the following:

```
C_INCLUDES = $(TGT_INCLUDES)                    \
             -I$(PATH_APP)                      \
             -I$(PATH_APP)/mcal/$(TGT)
```
While the linux build file `target/app/make/app_make_linux.gmk` has the following:

```
C_INCLUDES = -I$(PATH_APP)                      \
             -I$(PATH_APP)/mcal/$(TGT)
```

When I added the missing piece $(TGT_INCLUDES) everything appears to build fine.

**Comment by ckormanyos** [comment]
Yes. I regret that the Linux build is out of date. Another yes... a small subset of the STL is implemented in the directory that you mention. Great recognition from your side.

**Comment by gantzm** [comment]
Closing as the fix for this was accepted in a pull request.
