### ISSUE TITLE
A book review

### ISSUE THREAD

**Issue by yahyatawil** [ckormanyos/real-time-cpp#31]
Hello Chris 

This not a question nor a query. I just wanted to share with you the review I wrote about your great book.

https://atadiat.com/en/e-embedded-c-developers-hate-or-love-cpp/

I hope you like it. And sorry for sharing this here, but I couldn't find a personal email for you.

Best

**Comment by ckormanyos** [comment]
Thank you for sharing this review.
It has been visible for quite some time and I will now close the issue.
Kind regards, Chris
