### ISSUE TITLE
C++-ification of RP2040 mcal

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/real-time-cpp#526]
The RP2040 mcal has borrowed significantly from [Chalandi/Blinky_Pico_dual_core_nosdk](https://github.com/Chalandi/Blinky_Pico_dual_core_nosdk). His repo (many thanks for yet more excellent work from @Chalandi) was originally written in no-sdk, standalone C. To match styes, the purpose of this issue is to fully C++-ify those original (very helpful) components.

**Comment by ckormanyos** [comment]
Cc: @imahjoub this now boots and fully runs in standalone mode for RP2040. The Ozone debug files can be found in the expected target-specific area.

**Comment by ckormanyos** [comment]
Change the `Mcal` files one-by-one to be integrated in the normal C++ repo-style.

**Comment by ckormanyos** [comment]
And when it is done, remember to remove the temporary CMSIS license docs notes.

**Comment by imahjoub** [comment]
> Cc: @imahjoub this now boots and fully runs in standalone mode for RP2040. The Ozone debug files can be found in the expected target-specific area.

thank you @ckormanyos
