### ISSUE TITLE
Can the ref_app be built on mac host and run on the board?

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/real-time-cpp#8]
Some readers are using the ref_app on a mac host. Does the ref_app even work on a mac host, or does some adaption need to occur?

**Comment by thzoechbauer** [comment]
Hello Chris!

I'm using Windows but have a problem with hexmanip.exe too: it is missing and I can't figure out where to download it? Do I have to execute hexmanip.exe on the hex-file or can I comment this line out of app_make.gmk?

Thanks, Tom

**Comment by ckormanyos** [comment]
Thanks Tom. Please just comment out the line. The presence of the line is actually a bug. Sorry, I thought  had already corrected it. I will correct it next week. - Chris

**Comment by ckormanyos** [comment]
The hex-manip line has been removed from the build script. But this breaks raspi and beagle bone builds of object binaries. Therefore, make a new issue for the creation of a new generic hex-manip facility.

**Comment by ckormanyos** [comment]
The GNUmake scripts have been extended to include *nix compatibility. There are also new CMake scripts that probably run on the above-mentioned host.
